# Generated by Django 5.1 on 2024-09-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
    ]
